= Lab 1 - From Zero to Pushing Your First Application

[abstract]
--
The prime directive of Pivotal Cloud Foundry is to host applications. We are going to exercise that directive by pushing a very simple Spring application.

By the end of this lab you should have your spring-music application up and running in your account.
--

== Set your target environment

. If you haven't already, download the latest release of the Cloud Foundry CLI from https://github.com/cloudfoundry/cli/releases for your operating system and install it.

. Set the API target for the CLI:
+
----
$ cf api --skip-ssl-validation https://api.<DOMAIN_PROVIDED_BY_INSTRUCTOR>
----

. Login to Pivotal Cloud Foundry:
+
----
$ cf login
----
+
Follow the prompts, entering in the student credentials provided by the instructor and choosing the development space.

== Build (or Download) and Push!

Change to the _Spring Music_ sample application directory:
----
$ cd $COURSE_HOME/Labs/Lab01-Application_Push/cf-env
----

=== Push

Now use the `cf push` command to push the application to PCF!

----
$ cf push
----

You should see output similar to the following listing. Take a look at the listing callouts for a play-by-play of what's happening:

====
----
Using manifest file /Users/mling/PCF-Ops-Workshop/Labs/Lab01-Application_Push/cf-env/manifest.yml

Updating app cf-env-mling in org EPA / space mling as admin...
OK

Creating route cf-env-mling-emptiest-oviparousness.apps.cf.mingling.net...
OK

Binding cf-env-mling-emptiest-oviparousness.apps.cf.mingling.net to cf-env-mling...
OK

Uploading cf-env-mling...
Uploading app files from: /Users/mling/PCF-Ops-Workshop/Labs/Lab01-Application_Push/cf-env
Uploading 120.9K, 26 files
Done uploading
OK

Starting app cf-env-mling in org EPA / space mling as admin...
Downloading nodejs_buildpack...
Downloading java_buildpack_offline...
Downloading staticfile_buildpack...
Downloading binary_buildpack...
Downloaded binary_buildpack (9.3K)
Downloading python_buildpack...
Downloaded staticfile_buildpack (2.6M)
Downloading go_buildpack...
Downloading php_buildpack...
Downloaded nodejs_buildpack (109.4M)
Downloading ruby_buildpack...
Downloaded java_buildpack_offline (249.1M)
Downloading dotnet_core_buildpack...
Downloaded python_buildpack (255.3M)
Downloaded dotnet_core_buildpack (169.3M)
Downloaded ruby_buildpack (260.8M)
Downloaded php_buildpack (310.4M)
Downloaded go_buildpack (392M)
Creating container
Successfully created container
Downloading app package...
Downloaded app package (404.7K)
Staging...
-------> Buildpack version 1.7.16
file:///tmp/buildpacks/0e5cebf8cef53453ba2dd37a7b418c39/dependencies/https___buildpacks.cloudfoundry.org_dependencies_godep_godep-v75-linux-x64.tgz
file:///tmp/buildpacks/0e5cebf8cef53453ba2dd37a7b418c39/dependencies/https___buildpacks.cloudfoundry.org_dependencies_glide_glide-v0.12.3-linux-x64.tgz
-----> Checking Godeps/Godeps.json file.
-----> Installing go1.7.4... done
Downloaded [file:///tmp/buildpacks/0e5cebf8cef53453ba2dd37a7b418c39/dependencies/https___buildpacks.cloudfoundry.org_dependencies_go_go1.7.4.linux-amd64.tar.gz]
 !!    Installing package '.' (default)
 !!
 !!    vendor/ directory does not exist.
 !!
-----> Running: go install -v -tags cloudfoundry .
github.com/tracyde/cf-env
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (66.5M)
Uploaded droplet (2.8M)
Uploading complete
Destroying container

1 of 1 instances running

App started


OK

App cf-env-mling was started using this command `cf-env`

Showing health and status for app cf-env-mling in org EPA / space mling as admin...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: cf-env-mling-emptiest-oviparousness.apps.cf.mingling.net
last uploaded: Mon Mar 27 01:50:30 UTC 2017
stack: cflinuxfs2
buildpack: Go

     state     since                    cpu    memory       disk          details
#0   running   2017-03-26 09:52:28 PM   0.0%   3.4M of 1G   10.5M of 1G
----

<1> The CLI is using a manifest to provide necessary configuration details such as application name, memory to be allocated, and path to the application artifact.
Take a look at `manifest.yml` to see how.
<2> In most cases, the CLI indicates each Cloud Foundry API call as it happens.
In this case, the CLI has created an application record for _Spring Music_ in your assigned space.
<3> All HTTP/HTTPS requests to applications will flow through Cloud Foundry's front-end router called http://docs.cloudfoundry.org/concepts/architecture/router.html[(Go)Router].
Here the CLI is creating a route with random word tokens inserted (again, see `manifest.yml` for a hint!) to prevent route collisions across the default PCF domain.
<4> Now the CLI is _binding_ the created route to the application.
Routes can actually be bound to multiple applications to support techniques such as http://www.mattstine.com/2013/07/10/blue-green-deployments-on-cloudfoundry[blue-green deployments].
<5> The CLI finally uploads the application bits to PCF. Notice that it's uploading _90 files_! This is because Cloud Foundry actually explodes a ZIP artifact before uploading it for caching purposes.
<6> Now we begin the staging process. The https://github.com/cloudfoundry/java-buildpack[Java Buildpack] is responsible for assembling the runtime components necessary to run the application.
<7> Here we see the version of the JRE that has been chosen and installed.
<8> And here we see the version of Tomcat that has been chosen and installed.
<9> The complete package of your application and all of its necessary runtime components is called a _droplet_.
Here the droplet is being uploaded to PCF's internal blobstore so that it can be easily copied to one or more _http://docs.cloudfoundry.org/concepts/diego/diego-components.html#cell-components[Diego Cells]_ for execution.
<10> The CLI tells you exactly what command and argument set was used to start your application.
<11> Finally the CLI reports the current status of your application's health.
You can get the same output at any time by typing `cf app spring-music`.
====
